### ISSUE TITLE
Connection / authentication problem

### ISSUE THREAD

**Issue by wujastyk** [oxygenxml/oxygen-git-client-addon#180]
I've had to uninstall this plugin and move over to GitHub Desktop because the oxygenxml git plugin refuses to push commits.  I've tried everything I can think of.  The permissions on my `.ssh` directory are fine.  My ssh authentication works fine with the command line and with GitHub Desktop.  I'm stymied.  The error messages are lacunose and don't give me any leads ("can't push").

I'm on Linux Mint + Cinnamon, everything up to date.

**Comment by sorincarbunaru** [comment]
Hello!

I would be interested in taking a look at the Git Client logs, perhaps I can spot something fishy in there... For that, I need you to:
1. Download [logback.zip](https://github.com/user-attachments/files/16344073/logback.zip) and extract the XML file from inside it.
2. Copy the "logback.xml" file in the "lib" folder from the Oxygen XML Editor/Author/Developer installation directory.
3. Restart the application.
4. Reproduce the push problem.
5. Close the application. The resulting log files are named "oxygen.log" and "oxygen#.log.qz" (for example, oxygen.log, oxygen1.log.gz, oxygen2.log.gz, etc.) and are located in the "Desktop\oxygenLog" folder.
6. When done, delete the "logback.xml" file, because it may cause performance issues if left in the "lib" folder.
7. Add the "Desktop\oxygenLog" folder to an archive and send it to us at support@oxygenxml.com.

Best wishes!

**Comment by wujastyk** [comment]
Thank you for the step-by-step.  I attach the oxygen.log in a zip file, and
also a screenshot of the error message.

Best,
Dominik


--
Professor Dominik Wujastyk
<https://apps.ualberta.ca/directory/person/wujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History, Classics, and Religion
<http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.

**Comment by sorincarbunaru** [comment]
Unfortunately, I don't see the attachments.

**Comment by wujastyk** [comment]
Ah, github stripped them out.  I'll go to github and attach them there.


--
Professor Dominik Wujastyk
<https://apps.ualberta.ca/directory/person/wujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History, Classics, and Religion
<http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.


South Asia at the UofA:

sas.ualberta.ca

SSHRC research: The Suśruta Project <http://sushrutaproject.org>

Journal: History of Science in South Asia <http://hssa-journal.org>

**Comment by wujastyk** [comment]
[oxygenLog.zip](https://github.com/user-attachments/files/16362920/oxygenLog.zip)
![Screenshot from 2024-07-23 15-37-06](https://github.com/user-attachments/assets/da9a526c-2a83-4180-802f-8f982cde89e6)

**Comment by sorincarbunaru** [comment]
Hi again,

1. What version of the plugin were you using?
2. Has it ever worked for you with SSH authentication?
3. I would suppose the repo was not cloned using the Git Client Add-on, right? 
4. What you could quickly try is to reset the Git Client credentials and see that makes any changes:
![image](https://github.com/user-attachments/assets/0304e97f-1b19-498a-b629-523b9f7f2729)

**Comment by wujastyk** [comment]
On Thu, 25 Jul 2024 at 07:52, Sorin Carbunaru <notifications@github.com> wrote:

    Hi again,

        What version of the plugin were you using?

​The version of yesterday.  I fetched and installed it to do your test. 5.3.0

        Has it ever worked for you with SSH authentication?

​Yes, it worked fine until a few weeks ago.  I don't know what changed.  And plain CLI git, gh, and GitHub Desktop all work with ssh just fine.

        I would suppose the repo was not cloned using the Git Client Add-on, right?

​That's right.  I mostly work just with CLI git.

        What you could quickly try is to reset the Git Client credentials and see that makes any changes:
        [image.png (view on web)](https://github.com/user-attachments/assets/0304e97f-1b19-498a-b629-523b9f7f2729)


​I tried that before, no improvement.

I've just reset credentials again, and got this
On Thu, 25 Jul 2024 at 07:52, Sorin Carbunaru <notifications@github.com> wrote:

    Hi again,

        What version of the plugin were you using?

​The version of yesterday.  I fetched and installed it to do your test. 5.3.0

        Has it ever worked for you with SSH authentication?

​Yes, it worked fine until a few weeks ago.  I don't know what changed.  And plain CLI git, gh, and GitHub Desktop all work with ssh just fine.

        I would suppose the repo was not cloned using the Git Client Add-on, right?

​That's right.  I mostly work just with CLI git.
 

        What you could quickly try is to reset the Git Client credentials and see that makes any changes:
        [image.png (view on web)](https://github.com/user-attachments/assets/0304e97f-1b19-498a-b629-523b9f7f2729)


​I tried that before, no improvement.

I've just reset credentials again, and got this
![image](https://github.com/user-attachments/assets/d78fdd16-1716-4ea4-b5c8-f01b8e9274fb)

**Comment by sorincarbunaru** [comment]
This kind of issues, where everything went well for a while then suddenly something bad happened out of the blue, are quite difficult to understand... 

Have you changed anything in the SSH configuration lately? Maybe generated a new pair of keys?

What happens if you try to clone that repo to another location on your computer using the Git Client Oxygen add-on? Can you clone it successfully? If yes, can you then push some changes?

If you cannot clone the repo or push the changes, given the fact that you cannot use the Git Client anymore with SSH anyway, I guess we could try a sort of "hard reset". For that you would have to go to `[user_home_directory]/.com.oxygenxml.author`, look for the options file for your version (e.g. `oxyAuthorOptionsSa26.1.xml`) and delete all the entries that start with `PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.git` (they should be grouped together) + the entry with `PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.user.credentials.list`. Then try again cloning and pushing.

Let me know how it goes.

**Comment by wujastyk** [comment]
On Fri, 26 Jul 2024 at 08:11, Sorin Carbunaru <notifications@github.com> wrote:

    This kind of issues, where everything went well for a while then suddenly something bad happened out of the blue, are quite difficult to understand...

​Yes, I agree!   I have tried so many ideas, uninstalling, reinstalling, fiddling with `.git/config` etc. etc.  The one constant is that the CLI git works fine, and so does GitHub Desktop.
 
    Have you changed anything in the SSH configuration lately? Maybe generated a new pair of keys?

​No. Also, Github nowadays needs a special "Personal Access Token (PAT)".  I haven't changed that either.

    What happens if you try to clone that repo to another location on your computer using the Git Client Oxygen add-on? Can you clone it successfully? If yes, can you then push some changes?

Yes, I can clone, but I still can't "talk" to Github.

![image](https://github.com/user-attachments/assets/17c3d900-f896-4fed-8ecb-3d3796a5e648)


I just tried gitg to see if that worked, but I couldn't push and got the following error message:


![image](https://github.com/user-attachments/assets/cd981544-0e49-438d-a7f2-c6857432f0be)


It seems likely to me that this is the underlying problem affecting Oxygenxml too.  I'll work on it now.

**Comment by wujastyk** [comment]
I've just spent another couple of hours trying to solve this and I can't.  I'm giving up.  I will use CLI or Github Desktop.  I need to get on with work, not wander in the maze of ssh-land.

**Comment by wujastyk** [comment]
> If you cannot clone the repo or push the changes, given the fact that you cannot use the Git Client anymore with SSH anyway, I guess we could try a sort of "hard reset". For that you would have to go to `[user_home_directory]/.com.oxygenxml.author`, look for the options file for your version (e.g. `oxyAuthorOptionsSa26.1.xml`) and delete all the entries that start with `PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.git` (they should be grouped together) + the entry with `PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.user.credentials.list`. Then try again cloning and pushing.

After giving up, I thought I'd give this one last try.

I have a directory `~/.com.oxygenxml/`  (not -`.author`).

I followed your instructions, but no improvement.

**Comment by sorincarbunaru** [comment]
If you ever want to try again to make your repo work with the Oxygen Git Client, I would expect using another type of key should do the job.

You can generate a new key by following this procedure: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

I've read that, when generating an RSA key using the command from this procedure, SHA256 is used by default instead of the deprecated SHA1 used for your current key.

Then you need to add the new key to GitHub: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account.

After that, normally you should be able to work just fine with our Git client.

BTW, I also added an internal issue (ID = EXM-54715) to show a helpful error message when using RSA-SHA1 keys.

**Comment by wujastyk** [comment]
Yes, I did generate a new key, 
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+8eD/0hik9LWX9WsawpdGJUgDLc0isb2mBuisgDuoJ wujastyk@gmail.com
and uploaded it to github and did the ssh-add thing on my machine.

**Comment by sorincarbunaru** [comment]
What does gitg say now, with the new Ed25519 key?

**Comment by wujastyk** [comment]
I tried to pull (main at Github is now ahead) and got

[image: image.png]

--
Professor Dominik Wujastyk
<https://apps.ualberta.ca/directory/person/wujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History, Classics, and Religion
<http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.


South Asia at the UofA:

sas.ualberta.ca

SSHRC research: The Suśruta Project <http://sushrutaproject.org>

Journal: History of Science in South Asia <http://hssa-journal.org>

**Comment by sorincarbunaru** [comment]
@wujastyk, the image was not posted...

**Comment by wujastyk** [comment]
> @wujastyk, the image was not posted...

![image.png](https://github.com/user-attachments/assets/2632ca61-8078-4211-86f3-09ffaaf43771)

**Comment by sorincarbunaru** [comment]
Hello again,

If you go to the "SSH Connections" preferences page, how do your options look like?

![image](https://github.com/user-attachments/assets/19852b01-09e7-4ea9-8ea3-0c821e17b063)

**Comment by wujastyk** [comment]
I've moved over to using Github Desktop, which "just works".  I never solved the oXygenxml Git plugin issue.
